kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswallsource-pv
  labels:
    type: local
spec:
  storageClassName: glasswallsource
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/test-data"